service:
  name: typescript-trial-1

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  profile: slstest
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
    environment:
      DB_HOST: localhost
      DB_USER: motdbuser
      DB_PASS: password
      DB_NAME: mot2
